### PR TITLE
Weekly Render Script

### PR DESCRIPTION
**Pull request by ebrayton**
Works for local renders. Takes Main render node and renders to the dailies/renders/ folder.

### CODE REVIEW

**Comment by bkingery** [comment]
I don't know why, but there is some conflicts and I can't merge it until they are resolved.

**Comment by ebrayton** [comment]
Some specific conflicts?

**Comment by bkingery** [comment]
I don't know. You're going to have to fetch upstream

**Comment by ebrayton** [comment]
Should be good now.

**Comment by bkingery** [comment]
thanks!

**Pull request merged**
